name: .NET Core

on:
  push:
    paths-ignore:
      - 'Images/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create config files
      run: |
        echo "<Automation />" > automation.xml
        echo "<Configuration />" > hardware.xml
        echo "<Home />" > home.xml
      working-directory: ./HomeExplorer/wwwroot
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
